#!/bin/bash

if [ "$1" = "-o" ]
then
	outfile=$2
	fullfile=$3
else
	outfile=$3
	fullfile=$1
fi

java Main ${fullfile}
filename="${fullfile##*/}"
extension="${filename##*.}"
filename="${filename%.*}"

gcc -m32 -c myAssembly.s -o ${filename}.o
gcc -m32 -o ${outfile} ${filename}.o -L./myLib -lgrace

rm "myAssembly.s"
rm ${filename}.o

#echo "${filename} is compiled"



